---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.nginx.name }}
  name: {{ .Values.nginx.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: {{ .Values.nginx.image }}
        ports:
        - containerPort: {{ .Values.nginx.containerPort }}
        resources: {}
        volumeMounts:
        - name: {{ .Values.nginx.volumeMounts.name }}
          mountPath: {{ .Values.nginx.volumeMounts.mountPath }}
      volumes:
      - name: {{ .Values.nginx.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.nginx.volumes.claimName }}
      securityContext: {}
      serviceAccount: {{ .Values.nginx.volumes.serviceAccount }}
      serviceAccountName: {{ .Values.nginx.volumes.serviceAccount }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nginx.name }}
  name: {{ .Values.nginx.name }}
spec:
  ports:
  - name: {{ .Values.nginx.name }}
    port: {{ .Values.nginx.port }}
    protocol: {{ .Values.nginx.protocol }}
    targetPort: {{ .Values.nginx.targetPort }}
  selector:
    app: {{ .Values.nginx.name }}
  type: {{ .Values.nginx.type }}
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nginx
    weight: null
